### ISSUE TITLE
Regarding image upload in toolbar

### ISSUE THREAD

**Issue by vaibhavFullStackDev** [yimogit/yimo-vue-editor#1]
Hello,
Requirement is that like hideImgLink option, add option to hide only imgUpload and show imgLink with name hideImgUpload to hide only imgUpload

**Comment by yimogit** [comment]
Is this what you need? `<v-editor :config="{uploadImgUrl:null}"></v-editor>`

**Comment by yimogit** [comment]
if your need hide link image
![image](https://user-images.githubusercontent.com/15975059/54358016-57980800-469a-11e9-8c3f-c2a7c6ef802d.png)

```
 editorConfig: {
    hideLinkImg:true,
    uploadImgUrl:'http://localhost:2233/api/upload',
}
```
if you need hide upload component
![image](https://user-images.githubusercontent.com/15975059/54358061-6da5c880-469a-11e9-9b80-23faa99c0ceb.png)

```
editorConfig: {
   hideLinkImg:false,
   uploadImgUrl:null
}
```

**Comment by vaibhavFullStackDev** [comment]
Thanks @yimogit

**Comment by vaibhavFullStackDev** [comment]
It worked.
