### ISSUE TITLE
How to remove the console.log?

### ISSUE THREAD

**Issue by heliomsolivas** [yimogit/yimo-vue-editor#10]
I'm trying to remove the console.log message:

`wangEditor提示: 本页面富文本编辑器由 wangEditor 提供 http://wangeditor.github.io/ `

I've tried to add the config `printLog = false` but did not work.

Can anyone help me?

Example:

`public yimoConfig: {} = {
        menus: ['source', '|', 'bold', 'underline', 'italic', 'strikethrough', '|', 'head', 'unorderlist', 'orderlist', 'alignleft', 'aligncenter', 'alignright', '|', 'undo', 'redo'],
        printLog: false,
        lang: {
            bold: 'Bold',
            underline: 'Underline',
            italic: 'Italic',
        },
    };`

**Comment by yimogit** [comment]
This is the copyright prompt of the original author. The package has not been removed after consideration. If necessary, you can try to clone and modify it
About this discussion：https://github.com/wangeditor-team/wangEditor/pull/542
The code of the package：https://github.com/yimogit/yimo-vue-editor/blob/master/src/assets/js/wangEditor.js#L8433
