### ISSUE TITLE
Chinese characters in the editor table creation

### ISSUE THREAD

**Issue by zhijiangao** [yimogit/yimo-vue-editor#11]
set the language to 'en',  when you attempt to insert a table , the words  for columns and rows are display in Chinese (eg: 2行2列）.

**Comment by yimogit** [comment]
OK, we'll fix it later

**Comment by yimogit** [comment]
Fixed, And released a new version v1.1.6
![image](https://user-images.githubusercontent.com/15975059/99339414-1caf9400-28c1-11eb-9a30-cad51def9cf7.png)

**Comment by zhijiangao** [comment]
Thanks a lot!!!
