### ISSUE TITLE
How to call insertHtml under 'source' mode 

### ISSUE THREAD

**Issue by zhijiangao** [yimogit/yimo-vue-editor#12]
Hi, 
I am trying to  do insertHtml under source code mode. I am able to call the editor.command(event, 'insertHtml', string) under editor mode. just wondered if there's a way to do it under source mode ?

Thanks

**Comment by yimogit** [comment]
Do you mean you want to get the editor instance for operation？
want source mode to get `new E()` or `E` ？

I modified the source code, exposed the current instance out to achieve the following effect, do not know if you want

![image](https://user-images.githubusercontent.com/15975059/99479335-ef321b80-2990-11eb-9a3c-1a88f1345622.png)

**Comment by zhijiangao** [comment]
sorry, I mean when we press "</>" leftmost menu button, and try to add some content (eg: 'test') after the highlighted cursor. when in other mode,  I can call E.command(null, 'insertHtml', 'test'); but in this 'source' menu mode, I don't know how to insert the 'test' string after the cursor. Thanks

**Comment by yimogit** [comment]
Maybe this menu event should be rewritten
 [source](https://github.com/yimogit/yimo-vue-editor/blob/master/src/assets/js/wangEditor.js#L4106)
About rewriting, you can hide the menu and customize the source menu

**Comment by zhijiangao** [comment]
seems like in wangEditor 3 or 4, there is no more source edit function. can you expose the state to check if it's the 'source' mode?
(eg: isShowCode from the menu), thanks

**Comment by yimogit** [comment]
Temporarily unable to achieve, if necessary, you can own Tianji a source menu, customize
