### ISSUE TITLE
Cannot read property 'langs' of undefined

### ISSUE THREAD

**Issue by andreicrus** [yimogit/yimo-vue-editor#14]
Hi, can you help me with the following error:
Uncaught TypeError: Cannot read property 'langs' of undefined

My implementation is the following:
`import YimoVueEditor from 'yimo-vue-editor'
Vue.use(YimoVueEditor, {
    name: 'v-editor',
    config: {
        uploadImgUrl: null, 
        printLog: false, 
        lang: YimoVueEditor.E.langs.en
    }
})`

What I want to achieve is to upload the images in base64 format and set the language. Without language settings it looks like this:
![image](https://user-images.githubusercontent.com/5967072/124073305-a8d68c00-da4a-11eb-88ed-146ab23e0c6b.png)

**Comment by yimogit** [comment]
Try this
` useLang:'en'`

**Comment by andreicrus** [comment]
Awesome, it worked for the language. Thank you!
Can you help me with a resolution for embedded images(base64 format)?

**Comment by yimogit** [comment]
https://github.com/yimogit/yimo-vue-editor#parameter

You can configure the last interface and uploadhandler hook and return to Base64 directly
