### ISSUE TITLE
Document Support English

### ISSUE THREAD

**Issue by huuphuong** [yimogit/yimo-vue-editor#3]
I love your editor. It's simple, clean and useful. But when i want to read the documentation to use editor, i can't understand Chinese language. Can you support English document?
Thanks.

**Comment by yimogit** [comment]
I'm sorry. This project is based on wangEditor. There are no documents in other languages 

So, Use Google Translate~

this is v2.0 doc: https://www.kancloud.cn/wangfupeng/wangeditor2/113961
