### ISSUE TITLE
Regarding spacing

### ISSUE THREAD

**Issue by vaibhavFullStackDev** [yimogit/yimo-vue-editor#5]
When press the enter key on keyboard, cursor jumps two lines below in editor
How to take care of that

**Comment by vaibhavFullStackDev** [comment]
And also kindly help me out in below scenario
- How to insert/append any text/letter/word in editor, where cursor positioning currently
- In case of copy/paste word  or append/prepend/insert word

**Comment by yimogit** [comment]
I'm terribly sorry.The reply is a little late,  I don't quite understand what you mean.
if you can, I hope to your use GIF to illustrate it.
