### ISSUE TITLE
I need to add a custom button to the toolbar

### ISSUE THREAD

**Issue by nekooee** [yimogit/yimo-vue-editor#7]
Hi Dear,
I need to add a custom button to the toolbar to get images from my media manager.
can I add it? and how?

**Comment by yimogit** [comment]
Hi.
You can view the description of the menu in the wangedit document https://www.kancloud.cn/wangupeng/wangeditor2/115834

**Comment by nekooee** [comment]
> Hi.
> You can view the description of the menu in the wangedit document https://www.kancloud.cn/wangupeng/wangeditor2/115834

your link get error 404 not found!

**Comment by yimogit** [comment]
i'm sorry
That's right
https://www.kancloud.cn/wangfupeng/wangeditor2/115834
