### ISSUE TITLE
图片上传成功后，会多出一张base64的图片

### ISSUE THREAD

**Issue by kenjiding** [yimogit/yimo-vue-editor#8]
![image](https://user-images.githubusercontent.com/34638158/83849845-9d7b3900-a742-11ea-99b7-4267f158266c.png)
请问怎么解决？

**Comment by yimogit** [comment]
我测试了下，粘贴上传的就是会写入成base64，可以把粘贴上传图片禁用了

**Comment by kenjiding** [comment]
> 我测试了下，粘贴上传的就是会写入成base64，可以把粘贴上传图片禁用了
哪个配置可禁用呢

**Comment by yimogit** [comment]
去看了wangEditor2的文档，貌似没有专门的配置，如果你这边有需要，欢迎提下 pr 加个配置进行屏蔽
