### ISSUE TITLE
In Nuxt Error

### ISSUE THREAD

**Issue by reaink** [yimogit/yimo-vue-editor#9]
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <YimoVueEditor>

let E = null
if (process.browser) {
  E = require('yimo-vue-editor')
}

export default {
  components: {
    YimoVueEditor: E || null,
  },

**Comment by yimogit** [comment]
I don't quite understand. Maybe you can mention a PR?

**Comment by reaink** [comment]
@yimogit nuxt 中无法运行起来

**Comment by yimogit** [comment]
> @yimogit nuxt 中无法运行起来

```
<template>
  <div>
   <h2>yimo-vue-editor 在 Nuxt 的使用</h2>
    <yimo-vue-editor v-model="text" v-if="isInitEditor"/>
  </div>
</template>

<script>
import Vue from 'vue'
export default {
  components: {
  },
  data() {
    return {
      isInitEditor: false,
      text: ''
    }
  },
  mounted() {
    this.$nextTick(() => {
      var YimoVueEditor = require('yimo-vue-editor')
      Vue.use(YimoVueEditor, {
        name: 'yimo-vue-editor',
        config: {
          uploadPlaceholderImg: 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',
          menus: [
            'source',
            'img',
            'video',
            'insertcode',
            '|',
            'undo',
            'redo',
            'fullscreen'
          ]
        }
      })
      this.isInitEditor = true
    })
  }
}
</script>
```
我找了个 nuxt 项目试了下，如果需要在nuxt项目使用，可以参考上面代码使用哈
![image](https://user-images.githubusercontent.com/15975059/98890737-9ddce480-24d7-11eb-80c1-84c48a6cc710.png)

**Comment by reaink** [comment]
@yimogit 好的，谢谢
